### ISSUE TITLE
Ability usable aura does not seem to work.

### ISSUE THREAD

**Issue by atsolberg** [Geigerkind/ModifiedPowerAuras#12]
I've tried making a simple aura that shows when Arcane Shot is usable.  See screenshot: https://gyazo.com/8f22f983998b234222f5c37738106f97

As far as I can tell all I should need is the spell name, the `Show Cooldown` checked, `Invert` checked, and `In Combat` checked.  Am I missing something?

I had pulled the repo yesterday so using the latest code.

**Comment by tdymel** [comment]
It should show you the icon if it is not on cooldown and if you are in combat now.

**Comment by atsolberg** [comment]
Thx for the quick response.  The icon doesn't show in or out of combat, regardless of the `In Combat` checkbox state. I tried all combinations.  It does show when clicking the `Test` button.  It seems like maybe the `Invert` logic is messing it up?

**Comment by tdymel** [comment]
Fixed, thanks for the report!
