### ISSUE TITLE
Change the notation in the xml file

### ISSUE THREAD

**Issue by ghost** [Geigerkind/ModifiedPowerAuras#13]
Could you change all the lines containing _ICONS_ to _Icons_ ?

For example
`getglobal(this:GetName().."_Icon"):SetTexture("Interface\\ICONS\\Spell_Nature_Reincarnation")`

to

`getglobal(this:GetName().."_Icon"):SetTexture("Interface\\Icons\\Spell_Nature_Reincarnation")`

It causes a bug with a other addon (Zhuntermod)

**Comment by tdymel** [comment]
How is it interferring with this addon o.O?

**Comment by ghost** [comment]
**"ZHunterButtonTrack.lua" Line 77 -83**
`		local texture = ZHunterButtonTrack1IconTexture:GetTexture()
		local buff = GetTrackingTexture()
		if texture == buff and ZHunterButtonTrack2.id then
			ZHunterButtonTrack.id = ZHunterButtonTrack2.id
		else
			ZHunterButtonTrack.id = ZHunterButtonTrack1.id			
		end`

`ZHunterButtonTrack1IconTexture:GetTexture()` returns your file path with uppercase _\ICONS\_.

So the if function never become true.

**Comment by tdymel** [comment]
Have you tested it?
Because all it does in the xml is to put a arbitrary texture to an self created button. It shouldn't interfere at all. What is ZHuntermod doing exactly with these textures?

**Comment by ghost** [comment]
Yes I have tested it.
Disable MPOWA - Zhuntermod's Trackbutton works.
Enable MPOWA - Zhuntermod's Trackbutton doesn't work.
Keep MPOWA enabled and change all paths with `ICONS` to` Icons` in ModifiedPowerAuras.xml - Zhuntermod's Trackbutton works.
I don't know why `ZHunterButtonTrack1IconTexture:GetTexture()` returns your texture file path :(
It is just a suggestion to workaround the problem.
