### ISSUE TITLE
Add dynamic group feature like weakaura has on retail

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [Geigerkind/ModifiedPowerAuras#17]
With WeakAura (Pretty much retail's MPOWA addon) there's a feature called dynamic groups that you can put auras into, it will then sort all auras in that group depending on time left from left to right (or however you'd like) so you don't have to position your auras side by side in a static spot.

Hopefully that made sense, but if not then here's a video of someone showing his dynamic group auras on retail https://youtu.be/ZBTwrSPb4fw?t=1m42s

**Comment by Steffen-Hadberg-Nielsen** [comment]
So I guess this won't be happening or? 😕

**Comment by tdymel** [comment]
It has been implemented ;)
Though maybe not completly retail like ^^

**Comment by Steffen-Hadberg-Nielsen** [comment]
Ah I see, I was a little confused there :p

Thanks! 👍
