### ISSUE TITLE
Integrate Clean Icons

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [Geigerkind/ModifiedPowerAuras#18]
Would appreciate if you could integrate Clean Icons as they look far better than the default icons with the ugly borders

http://www.wowinterface.com/downloads/info19844-CleanIcons-Thin.html

**Comment by tdymel** [comment]
That is nothing I can alter
You have to download it and put it into your icons folder.
I won't add them beside the original ones
