### ISSUE TITLE
Add support for tracking combo points

### ISSUE THREAD

**Issue by opeter94** [Geigerkind/ModifiedPowerAuras#19]
Hey,

Title pretty much says it all, it's implemented in WOTLK Power Auras too, if you could backport it/do it yourself it would be much appreciated! :)

**Comment by tdymel** [comment]
Added

**Comment by opeter94** [comment]
Not working for me at all, could you please check, and give some instructions how to use it? e.g. do I have to give a buff name or just simply set the number of CPs i want to track and thats it?

Thanks

**Comment by tdymel** [comment]
It is just an extra condition. It uses the amount of GetComboPoints("player", "target").
 ">=0" => always 
 ">=1" => higher eqal 1 etc.

**Comment by opeter94** [comment]
So I can't track combo points, just use the number of CPs as a condition to track other buffs?

**Comment by tdymel** [comment]
Yes, to track combo points I would suggest an unitframe addon

How exactly did you imagined it?

**Comment by opeter94** [comment]
OK I understand now. I thought about the feature to be able to actually track CPs all along, not an extra condition with CPs. A little misunderstanding, I guess. I'll use another addon for it then. Thanks.

Edit: What I was thinking about: https://youtu.be/55kCLFKwiPU?t=181

**Comment by RUTHINAS** [comment]
Old issue, but I find it to be relevant nevertheless. I would also like the kind of combo point tracker opeter94 described. The sheer configurability of MPOWA is exactly what I look for in a combo tracker, as I can essentially create an entire in-combat HUD from scratch, animations and sound effects included. In the current iteration, sadly, it is not possible. I even considered having a constantly active buff that the aura(s) would be tracking, and then displaying and hiding them conditionally based on combo point amounts. It becomes tedious, however, as one can not always have the buff active.
