### ISSUE TITLE
Stacklaufzeiten werden nicht aktualisiert

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/ModifiedPowerAuras#21]
Hey Geigerkind (hab dir zwar schon auf MMOBase ne Pm geschrieben aber egal),

ich hätte mal wieder ein Anliegen und würde wissen ob dies überhaupt möglich ist. Und zwar hab ich nun dank Mpowa ein Icon für die Feuerverwundbarkeit mit Timer sowie Stackanzahl, soweit sogut ^^
Nun besteht leider noch das Problem das ich diesen Debuff auf dem Gegner 5mal stacken kann wobei die Laufzeit jeweils 30sek ist. Problem ist nun nur, das er den Timer nicht erneuert wenn ich vom 1 Stack auf den 2ten gehe, sondern der Timer einfach weiter runter läuft von besagten 30sek.
Dieser resettet sich dann nach Ablauf dieser 30sek wieder auf die vollen 30sek. - sprich, man weiss nie genau wie lange sich nun der Debuff noch auf den Mob befindet. Gibt es eine Möglichkeit dies zu erreichen?

Mfg der Mixus

Edit meint ausserdem: Diesen Debuff können auch andere Feuer-Mages die dieses Talent *Verbessertes Versengen* geskillt haben, auf dem jeweiligen Mob casten/aufrecht halten.

**Comment by tdymel** [comment]
Eig nicht, wenn nur ne hacky methode :/
Es gibt kein Event, dass abgefeuert wird, wenn sich ein stack refreshed wird. Wurde in TBC eingeführt.

Habe mal zumindest bis 5 stacks ein workaround eingeführt. Danach kann man nichts mehr machen, sorry

**Comment by Mixuspidelix** [comment]
leider resettet sich der Timer dauerhaft :s ka ob Du daran nochmal was ändern kannst? ansonsten danke für die Hilfe
