### ISSUE TITLE
Stacklaufzeiten bleiben nun bei 29/30sek stehen

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/ModifiedPowerAuras#23]
Hey Geigerkind, leider resettet sich der Timer nun dauerhaft :s ka ob Du daran nochmal was ändern kannst? Trotzdessen, sei nochmal gesagt: *Danke für den Versuch/für die Hilfe.*

**Comment by tdymel** [comment]
Ok, schau ich mir nach meinen Klausuren an :)

**Comment by tdymel** [comment]
Hmm, hab ich so jetzt eher weniger Probleme mit :/

Was genau machst du denn?

**Comment by tdymel** [comment]
Funktioniert, kann das Problem nicht reproduzieren.

**Comment by tdymel** [comment]
Ok, weiß, was du meintest
