### ISSUE TITLE
Can't /mpowa without getting error

### ISSUE THREAD

**Issue by Warriorgamersunite** [Geigerkind/ModifiedPowerAuras#24]
http://imgur.com/a/NWVMQ

Interface\AddOns\ModifiedPowerAuras\GUI.lua:157: attempt to index field `?' (a nil value)

Updated to build 32 since I had some trouble with a few auras in an old version (6months since I got it or so). Getting this error when I type /mpowa - Tried deleting the files from wtf folder etc, still having the same issue. 

Any suggestions would be very welcome!

**Comment by tdymel** [comment]
Use the previous build for now, I am going to fix it after my exams.
cheers!

**Comment by Warriorgamersunite** [comment]
Apparently a problem on my end, so just ignore this! Had to dl a new wow client etc, working perfectly now. Good luck with the exams! :)

**Comment by tdymel** [comment]
ok, will close it then!
Thanks ! :>
