### ISSUE TITLE
Mass errors on debuff aura

### ISSUE THREAD

**Issue by GregoryGH** [Geigerkind/ModifiedPowerAuras#27]
[2017/02/20 21:28:30-348]: ModifiedPowerAuras\Auras.lua:213: attempt to perform arithmetic on field `?' (a nil value)
ModifiedPowerAuras\Auras.lua:213: in function `GetDuration'
ModifiedPowerAuras\Auras.lua:146: in function `OnUpdate'
ModifiedPowerAuras\Start.lua:222: in function <Interface\AddOns\ModifiedPowerAuras\Start.lua:222>

![image](https://cloud.githubusercontent.com/assets/9971731/23139541/f46e3da8-f7bd-11e6-97d9-075ae046af2c.png)

**Comment by tdymel** [comment]
Hey, just to make sure, which build are you using?

**Comment by GregoryGH** [comment]
b33. is it fixed in b34?

2017-02-21 14:55 GMT+03:00 Tom Dymel <notifications@github.com>:

**Comment by tdymel** [comment]
Yep.
https://github.com/Geigerkind/ModifiedPowerAuras/issues/26
I fixed that in b34.

Thank you for reporting it anyway. Please hit me up if it appears in b34.
cheers!
