### ISSUE TITLE
Lua Error (AnimationGroup)

### ISSUE THREAD

**Issue by yutsuku** [Geigerkind/ModifiedPowerAuras#31]
![wowscrnshot_031717_195811](https://cloud.githubusercontent.com/assets/1192561/24059882/035d7170-0b51-11e7-84c8-378faaa30e28.jpg)

Still have no idea how to reproduce so I'll only describe what happened just before it.

My cooldown on "Preparation" just finished and now I was able to use it again.
After it the animation started to repeatedly fade out, repeating the error message every cycle.

Used conditions (in text, because for some reason AddOn disables my screenshot key):
* Exact name: Preparation
* Stacks: >=0
* CP: >=0
* On Cooldown: true
* Is Alive: true

**Comment by tdymel** [comment]
Fixed it.

**Comment by tdymel** [comment]
Thy
