### ISSUE TITLE
Lua:119

### ISSUE THREAD

**Issue by Epixmage** [Geigerkind/ModifiedPowerAuras#32]
Hey, i got this error after installing it for Elysium:
Interface\AddOns\ModifiedPowerAuras\GUI.lua:119:attempt to concatenate global `icopoth' (a nil value)

Followed all steps, and reinstalled twice.

**Comment by Road-block** [comment]
Sounds like a typo.  
Open GUI.lua in a text editor, search for icopoth and replace it with `icopath`

**Comment by tdymel** [comment]
Fixed :>
