### ISSUE TITLE
invert function with enemy debuff (stacks of debuff) not working

### ISSUE THREAD

**Issue by Ayzkronos** [Geigerkind/ModifiedPowerAuras#33]
Invert function don't seem to work when you specify a certain amount of stacks.

**What im trying to get it to do:**
I would like the icon to show when there is 0, 1, 2, 3 or 4 stacks of Fire Vulnerability on the enemy target, and hide the icon _only_ when there are 5 stacks of it.

**What it's doing:**
The icon shows when there are 0 stacks of the Fire Vulnerability up. The icon goes away when there is 1, 2, 3, 4 or 5 stacks up.

see screenshot
http://i.imgur.com/sqqS1Rp.jpg

**Comment by tdymel** [comment]
http://i.imgur.com/VQOEc6O.png

Do it like this.

Edit: Sorry it took me so long ^^
