### ISSUE TITLE
Bug: Mpowa menu cannot be opened

### ISSUE THREAD

**Issue by Ayzkronos** [Geigerkind/ModifiedPowerAuras#36]
Reproduce this by:

Create an Mpowa function
Then create another Mpowa function with the same name
Delete one of them
Close Mpowa
Try to open Mpowa again.
Mpowa won't open and instead gives this error:
http://i.imgur.com/Yf4JXsx.png

**Comment by tdymel** [comment]
Should be fixed. Thy for the report!
