### ISSUE TITLE
Add/Fix support to have multiple auras track the same buff/debuff/CD

### ISSUE THREAD

**Issue by kxseven** [Geigerkind/ModifiedPowerAuras#37]
## Use Case:
 - I would like to display the spell icon when the CD is ready/available
 - I would like a 2nd aura (in exactly the same location) to track the CD as it ticks back to 'ready' state with an icon using a red tint

## Problem
 - If I create both auras and try to use them the configuration of both auras appears to get 'confused' in the UI and requires a logout/login to safely store and re-load the correct configuration

## Workaround
 - Create both auras, logout, login again

## Suggestion
 - Add the ability to name auras and use that as the value for table lookups, rather than the aura name so that multiple auras tracking the same buff/debuff/CD can be used

## Example

![spell_ready](https://user-images.githubusercontent.com/11297100/26934027-1766d88c-4c60-11e7-9987-ac8f4e47869b.PNG)

![spell_cooldown](https://user-images.githubusercontent.com/11297100/26934037-1b941924-4c60-11e7-8e84-2a7f4cbb3e14.PNG)

**Comment by tdymel** [comment]
It does not use the name as lookup key^^ But I will lookup where the issue lies.

**Comment by tdymel** [comment]
Cant reproduce it.

**Comment by kxseven** [comment]
Understood. If I can reproduce it reliably I'll make a video and necro the issue.

**Comment by tdymel** [comment]
Alright, thanks :>
