### ISSUE TITLE
Timer for CDs is decrementing incorrectly

### ISSUE THREAD

**Issue by kxseven** [Geigerkind/ModifiedPowerAuras#38]
## Problem
 - When tracking a CD the counter (eg 15 seconds) tracks back from to 0 (15 ticks), rather than to 1
 - See image in URL for example

![spell_cooldown](https://user-images.githubusercontent.com/11297100/26933996-050d3cbc-4c60-11e7-8559-1b58727275ab.PNG)

**Comment by kxseven** [comment]
Basic fix applied and tested
https://github.com/Geigerkind/ModifiedPowerAuras/pull/40

More changes may be needed for the comparison; The '<=' may need changing to '<' but I don't know the codebase well enough to tell yet

**Comment by tdymel** [comment]
Looks fine to me, thanks!
