### ISSUE TITLE
Feature Request | Add ability to specify X,Y as numbers

### ISSUE THREAD

**Issue by kxseven** [Geigerkind/ModifiedPowerAuras#39]
## Problem
 - The current sliders do not appear to go up and down consistently, making it very difficult to get multiple auras aligned to the same X or Y co-ordinates

## Feature
 - Allow the X and Y values to be set as numbers as in the original PowerAuras

![image](https://user-images.githubusercontent.com/11297100/26936067-80af3898-4c65-11e7-917d-138f5a2eda42.png)

**Comment by tdymel** [comment]
Added
