### ISSUE TITLE
Feature Request | Support for Player Power (mana,rage,focus)

### ISSUE THREAD

**Issue by kxseven** [Geigerkind/ModifiedPowerAuras#41]
## Description

 - Add support for a special keyword in the buff input `playerpower` that checks the player power (`UnitMana("player")`) against the value defined in `stacks`
 - This can then be used to activate Auras if the player has more than X rage/mana/focus, etc
 - Ideally the ìnvert` checkbox would behave as expected too - when checked show the Aura if the player does NOT have more than X rage/mana/focus

![image](https://user-images.githubusercontent.com/11297100/27148254-851c8558-5137-11e7-887c-da78d598ce4c.png)

**Comment by tdymel** [comment]
Implemented as "unitpower"
