### ISSUE TITLE
lua-init-error

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/ModifiedPowerAuras#42]
http://www.bilder-upload.eu/show.php?file=875ab1-1498586233.png new lua-error with the newest master-version

**Comment by taurenrogue** [comment]
^same error here 2

**Comment by tdymel** [comment]
Fixed, I hope^^

**Comment by Mixuspidelix** [comment]
leider nein, error ist immer noch vorhanden :(

**Comment by tdymel** [comment]
Nu aber
