### ISSUE TITLE
Removing Auras messing up other auras

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#44]
First of all: I really love your addons, but they are buggy as hell. Now i start to report them because it seems like no one else does.

I tested this in version 45 and 48. I guess it's the same in the newest version. I do not use the newest version because it appears to be even more buggy (like constant lua errors in the chatlog).

Removing an aura which is not the last aura in the list (e.g. i got 20 auras and i delete aura 15), some other auras vanish or get a this black questionmark symbol, without any settings.
When looking into the savedvariable file, mpowa just delets the content of an array, but the array stays.
Not sure if this helps you understand my problem, but basically removing auras is destroying most of the previews settings in other auras.

**Comment by tdymel** [comment]
These lua errors would also help me to fix these issues.
As you may see not many report issues and I can't notice them cause I am not playing anymore.

But thanks for these reports, will see if I can fix them soonish. Currently its a little difficult cause I am in the middle of endterms.

cheers!

**Comment by tdymel** [comment]
Fixed
