### ISSUE TITLE
Invert Debuff Check not working

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#45]
https://gyazo.com/892a508c4d224021b6ccc97dfac6eecb
I want to archieve:
Check if the enemy has debuff "Sunder Armor", if not, then show the Icon. If yes, hide the icon.
Only if: In Raid and in Combat.

It does not work. Either the icon flashes (it shouldn't flash) or stays when unclicking the enemy.

**Comment by tdymel** [comment]
Fixed, also doesnt flash for me during tests.
