### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#46]
When i activate the following macro (using castmodifier macro), the juju flurry icon won't be shown.
It should show this (without adrenaline rush):
https://gyazo.com/28fdb95f5019bf8df1add0a3920fb237

But instead of showing juju flurry, it's just empty space. Like the icon is there but at 0% opacity.

![image](https://user-images.githubusercontent.com/27591842/27828092-bfa0d16a-60ba-11e7-8b5b-cdae8195bc92.png)

Also i don'T think it's macro related, it's rather, if too many auras get popped at once, then it bugs out.

/script if nil then CastSpellByName("Blade Flurry"); end
/cast [combat mypower>25]Blade Flurry
/script SpellStopCasting()
/use [combat mypower>25]Earthstrike
/use [group:raid mypower>25 nomybuff:Juju_Flurry]Juju Flurry

**Comment by tdymel** [comment]
Fixed
