### ISSUE TITLE
Mpowa gets messed up after client crash

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#47]
If the client crashes, while you are or have changed settings in mpowa, the savedvariable files get messed up leading to a non usable mpowa. Deleting savedvariable files and remaking all settings is the only way to go, which is really nervwrecking.

**Comment by taurenrogue** [comment]
This is true for half the addons in bc and vanilla?
solution = backup your WTF folder... often

**Comment by tdymel** [comment]
Its a simple problem. I am having one huge array that saves all data. When you access it and it crashes it can't put it back together.

A simple solution is to load it and save it at the very end again. I will look into it after my exam period

cheers!

**Comment by tdymel** [comment]
Should be prevented more reliably now
