### ISSUE TITLE
Mpowa is closing my client randomly during raid

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#48]
If i raid with mpowa enabled, my client crashes randomly to desktop without any errormessage (like alt+f4), Usually it happens midfight - not often, but 1 or 2 times per raid (60 minutes).
Here you will find my savedvariable file. It would be awesome if it gets fixed.

Since i raid without mpowa, i don't experience any crashes anymore - didn't change anything else.

Here you will find my modifiedpowerauras.lua:
https://drive.google.com/file/d/0B7Y-MwNxFwxnbl9VZ1RGQ242QVU/view?usp=sharing

**Comment by tdymel** [comment]
Interesting.
I assume you use the latest version.
Can you tell me after how much time it usually occours?

Maybe some memory leak related issue :/ Dunno
Will see after my exams.

**Comment by moootv** [comment]
I used b48.

I did a fresh install of the newest version now, also deleted the lua files to have a fresh setup and setup only 3 basic auras. I will test it in the next raid.

I already experienced a lua error, reported here https://github.com/Geigerkind/ModifiedPowerAuras/issues/49

**Comment by tdymel** [comment]
Alright. Thanks!

**Comment by tdymel** [comment]
Can you please remove the fadein/out animation from your auras and test if you still get these closings?

**Comment by tdymel** [comment]
I think this may have been related to another issue.
If it still occours in the new version, open a new ticket please!
