### ISSUE TITLE
error: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#49]
This error occured randomly. Newest version of mpowa (b52).
https://gyazo.com/58e4d8ab124f40f7f6f998a346f0d694

**Comment by moootv** [comment]
https://gyazo.com/c203e90f2d72ec0bffadee49bd8714f9

**Comment by tdymel** [comment]
Should not cause an issue anymore, else reopen.
