### ISSUE TITLE
b53 not saving auras

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#50]
I just created an aura without any fancy settings for Slice and Dice, activated timer.

After reloading the UI, and opening /mpowa the aura is gone.

**Comment by tdymel** [comment]
Remind me: Also fix it at TBC

**Comment by Mixuspidelix** [comment]
http://www.bilder-upload.eu/show.php?file=9b1095-1500122731.jpg hab das Problem auch und bekomme diese Fehlermeldung noch nebenher. Löschen der Dateien und das neu erstellen der Auren brachte leider keinen Erfolg. Fehler kommt nach dem erneuten aus/einloggen einfach wieder.

**Comment by Hadrilkar** [comment]
Bump.  Also experiencing this problem.

**Comment by tdymel** [comment]
Fixed
