### ISSUE TITLE
ModifiedPowerAuras.lua:2:: Attempt to index global 'self' (a nil value)

### ISSUE THREAD

**Issue by niight91** [Geigerkind/ModifiedPowerAuras#53]
rip addon... it was a cool addon because u could do some cooldown stuff which made it a kind of simplified TellMeWhen or WeakAuras for vanilla... but it seems u brokesed it

**Comment by Hadrilkar** [comment]
I also have this error.  Along with game freezing.

Not sure if Im doing something wrong, but when I log any auras I set up are gone upon relog, and the saved ones I try to import dont work.

**Comment by tdymel** [comment]
Fixed, sorry about that
