### ISSUE TITLE
Removing an aura results in LUA Error Spam

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#54]
Newest Version. I created a new aura, then removed it.
Result is a lua error spam (1 per second):
https://gyazo.com/f4586ac0acd033482cf9e79f29092e57

/reloadui seems to fix it.

Can you focus on making a super stable and reliable version? I really need it for upcoming naxx progress.

**Comment by tdymel** [comment]
Well, its hard to make something super stable if you don't play yourself^^

It passes my tests but Its hard to test all corner cases :/

**Comment by tdymel** [comment]
Fixed
