### ISSUE TITLE
Mpowa spuckt 3 Lua-Fehler aus

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/ModifiedPowerAuras#55]
habe nun 3 Lua-Fehler seit der neuesten Version 55 - die bisher stabilste Version ist bei mit die 48. Alles was danach kommt, spackt total rum :( 
http://www.bilder-upload.eu/show.php?file=25b5f5-1500578264.jpg
http://www.bilder-upload.eu/show.php?file=f91fa3-1500578292.jpg
http://www.bilder-upload.eu/show.php?file=8e748f-1500578305.jpg

**Comment by tdymel** [comment]
Sorry, dafür, ich versuche die Fehler so fix wie möglich zu beheben.

**Comment by Mixuspidelix** [comment]
Kein Ding ^^ bin froh das es dieses Addon überhaupt gibt und das Du versuchst alle Feher zu beseitigen 👍

**Comment by tdymel** [comment]
Kann den ersten nicht reproduzieren, aber sonnst sollte es funktionieren
