### ISSUE TITLE
Game Freezing

### ISSUE THREAD

**Issue by Hadrilkar** [Geigerkind/ModifiedPowerAuras#56]
Disabled all addons to test if it still happened with only MPA running and it did.

Causing wow to freeze.  Has to be shut down via  task manager.

Seems to happen mostly when an aura is active.

Tried timers on/off
Disabled Render + animations.

Halp :(

**Comment by 62574353** [comment]
Same thing is happening to me. Complete client freeze. I can't reproduce it, and it only seems to happen in raids although all my MPOWA's are "Raid Only."

I'm not using any crazy animations or anything like that. Almost all of the functions I use were available during a copy I downloaded last year. I've upgraded in the last month.

**Comment by tdymel** [comment]
Please upload your configuration file and the version you use. Also try to pinpoint a little more when it happens.

cheers!

**Comment by 62574353** [comment]
@Geigerkind 

I use build 48.

Unfortunately it doesn't seem to be caused by anything I can identify, but it occurs every raid. It's happened to me a number of times but in recent memory I can recall: during the AQ40 tunnel and during Chromaggus. I don't have any triggers associated with those particular events.

Where can I find the configuration file and what's the best means to upload it? Thanks for your time--have a great day.

**Comment by Hadrilkar** [comment]
Using build 55.  Which file is configuration file?

I've noticed is happens more frequently when Quick Shots has 3 seconds left.  It has frozen more at that point than any other.  But does freeze under different circumstances.

[MPA.zip](https://github.com/Geigerkind/ModifiedPowerAuras/files/1168028/MPA.zip)

**Comment by tdymel** [comment]
Hey!
It is located in your character saved variables and called "ModifiedPowerAuras.lua".

cheers!

**Comment by Hadrilkar** [comment]
Here is my file. Build 55.

[MPA.zip](https://github.com/Geigerkind/ModifiedPowerAuras/files/1168029/MPA.zip)

**Comment by tdymel** [comment]
Thank you. Will see if I can identify the issue!

**Comment by tdymel** [comment]
Hey think I may have found the issue.
Please test if it occours with the new version.
If so open a new issue please!
