### ISSUE TITLE
Bug -  Debuff Auras don't align correctly

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#61]
https://gyazo.com/2553ab42de28c1db84d38bd5a5a9e940

https://gyazo.com/08fdc53071f8e6438d9df6a9a60ef1a8

https://gyazo.com/625cf0fd98f9b852633a7be2393a1ed3

**Comment by moootv** [comment]
It seems like this is only happening if you check "Invert" - But since i need that option, would be great if you fix it.

**Comment by tdymel** [comment]
Fixed
