### ISSUE TITLE
Inverted Debuff Auras on Enemies

### ISSUE THREAD

**Issue by moootv** [Geigerkind/ModifiedPowerAuras#63]
When  I apply the dynamic group debuff aura to a mob all other auras fade out too.
E.g. i setup two debuffs:
Serpent Sting
Concussive Shot

I want to see the aura icons if the debuffs are NOT applied.
Works so far.

When i apply Concussive shot (which refers to the dynamic group of Serpent Sting) the icon fades out coprrectly.
But when i apply Serpent Sting, the Aura Icon of Concussive Shot fades out, too - even when concussive shot is not applied.

**Comment by tdymel** [comment]
Ok.
Can you make a video?
