### ISSUE TITLE
Game still freezes, build 62.

### ISSUE THREAD

**Issue by Godtvelox** [Geigerkind/ModifiedPowerAuras#65]
https://github.com/Geigerkind/ModifiedPowerAuras/issues/56

I've frozen around 10 times, with no freezes when this addon has been deactivated.

Currently testing without any active auras to see if that makes a difference.

Earlier I've been doing:
- inverted auras on Battle Shout
- seconds left on target debuffs with animated timers (mortal strike, hamstring, rend)
- seconds left on buff with animated timers (Battle Shout)

**Comment by tdymel** [comment]
Alright, looking forward to the test results!

**Comment by drtakhs** [comment]
I have the same problem. Here is what my config file looks like:


[ModifiedPowerAuras.zip](https://github.com/Geigerkind/ModifiedPowerAuras/files/1208890/ModifiedPowerAuras.zip)

By the way, I've had my first two auras forever and i never had any problem. Freezing started after i added the rest.

Hope this helps!

**Comment by Godtvelox** [comment]
Still no crashes with empty config (no auras) and all other settings and addons the same. 

I can recreate my auras and send my config file.


E:
Recreated the auras, and froze within 5 minutes of pvping.

[Modifiedpowerauras.lua.zip](https://github.com/Geigerkind/ModifiedPowerAuras/files/1209060/Modifiedpowerauras.lua.zip)

**Comment by tdymel** [comment]
That may help, but please reduce aura type by aura type to pinpoint which feature is causing these freezes.

Ex: Animations, Cooldown, Enemey target etc.

**Comment by 62574353** [comment]
Still crashing for me as well.

**Comment by Godtvelox** [comment]
Narrowed it down to one aura now. Reducing the selected options one by one while doing battlegrounds.

Last thing I had that crashed:

Ability: Doesnt matter
If X sec, left  (5 seconds)
Enemy Target
Is Debuff
Flash Animation on Timer

**Comment by tdymel** [comment]
Amazing, thanks!

**Comment by drtakhs** [comment]
Last thing I had that crashed:

**Ability: Doesnt matter**
**If X sec, left (60 seconds)**
Enemy Target : False
Is Debuff : False
**Flash Animation on Timer**

3/5 things you mentioned are part of the auras that crash my client as well

btw i am on latest release b59

**Comment by Godtvelox** [comment]
Just realized I posted this in the Vanilla instead of TBC version. I guess the problem exists for both versions!

It's definitely the **Flash Animation** that crashes the game.

Added new auras for my own buffs with only timer & flash animation enabled and it crashed (only timer never crashed)

It seems to happen right before/after a buff/debuff expires.

**Comment by tdymel** [comment]
Alright, thanks!
Will try to solve the issue for both clients after my exams!
cheers!

**Comment by pedro-cf** [comment]
I also get these crashes sadly. I've tried using the latest version, b57 and b48. One thing to note is that the crash always happens to me when an aura is at 3 seconds left, not sure if noteworthy or just a coincidence.

**Comment by tdymel** [comment]
There is an option called seconds left, do you use that by any chance^^ ?

**Comment by pedro-cf** [comment]
No, I think it is related with the flashing animation option. Haven't had the game crash when I didn't enable it.

**Comment by 62574353** [comment]
Any updates @Geigerkind ? MPOWA is essential for me and I'd love to be able to update it! Thanks for all your hard work and dedication. Rogues unite.

**Comment by drtakhs** [comment]
The problem comes down to flashing animation option found under "Timer" options.
I remade all my 17 auras without the option and it's working like a charm, it's a good solution until @Geigerkind is done with his exams.

good luck

**Comment by 62574353** [comment]
Unfortunately the timer flashes are essential for my setup. Currently using an older, more stable, but less robust version.

**Comment by tdymel** [comment]
I write my exam on the 20th september. I will start working on it then :>

**Comment by tdymel** [comment]
Try the latest commit of the master branch!

**Comment by tdymel** [comment]
Seems to work, since no respose :>
