### ISSUE TITLE
playing sound files error

### ISSUE THREAD

**Issue by brolernus** [Geigerkind/ModifiedPowerAuras#68]
line 87 \Animation.lua:
PlaySoundFile("Interface\\AddOns\\ModifiedPowerAuras\\Sounds\\"..self.SOUND[path.beginsound], "master")
should be:
PlaySoundFile("Interface\\AddOns\\ModifiedPowerAuras\\Sounds\\"..self.SOUND[p.beginsound], "master")

**Comment by tdymel** [comment]
Thanks!
