### ISSUE TITLE
"In Party"/"In Raid"

### ISSUE THREAD

**Issue by brolernus** [Geigerkind/ModifiedPowerAuras#70]
With the current version buffs will still show when having both of these options checked even without the condition. I haven't done extensive testing regarding the other options.
![mpowa](https://user-images.githubusercontent.com/24928956/32326472-3ba0db08-bfd3-11e7-85ab-099fdd539f14.PNG)
I was not in raid nor in any group when taking this picture

**Comment by tdymel** [comment]
Should be fixed now
