### ISSUE TITLE
Option: Wenn X sek. über funzt net

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/ModifiedPowerAuras#71]
Hallöchen,

habe gerade fest gestellt das in der aktuellen Version die Option: *Wenn X sek. über* sind, wohl net funktioniert. Habe mir einen Warri erstellt und das Schlachtruf-Symbol sollte aufploppen wenn vom Spell noch 15sek über sind. Leider ploppt es erst auf, wenn es komplett ausgelaufen ist.
Ausserdem scheint ein weiteres Problem mit den Animationen vorzuliegen da ich auch dort eine Lua-Fehlermeldung bekomme.
Interface\Addons\ModifiedPowerAuras\Animation.lua:117 attempt to index field `rotateanmin' (a nil value)
sowie 
Interface\Addons\ModifiedPowerAuras\Animation.lua:50 attempt to index field `rotateanmin' (a nil value)
Hoffe es hilft Dir weiter und Danke der Mixus :)

**Comment by tdymel** [comment]
Sollte nu funktionieren :>
