### ISSUE TITLE
Animation.lua ohne Ende Errors.

### ISSUE THREAD

**Issue by OhVook** [Geigerkind/ModifiedPowerAuras#73]
Hallo Geigerkind, Danke für das tolle Addon. Leider Spinnen bei mir die Animationen. Frisch geladen klappt nur der Batman und die Drehung, sonst nix. Dann aber, wenn der batman o. die Drehung einmal liefen, klappen auch andere sachen wie Fade usw.- Hab ein bisschen rumgespielt und auf Video festgehalten.
Hier zu sehen: https://youtu.be/ovkwqvemHj0

**Comment by tdymel** [comment]
Sollte nu funktionieren, danke

**Comment by OhVook** [comment]
So geil, nach all der Zeit komm doch noch ein Fix. Du bist n'geile Socke. Danke!
