### ISSUE TITLE
Unable to get Enemy Target + Invert working together.

### ISSUE THREAD

**Issue by Wushengg** [Geigerkind/ModifiedPowerAuras#74]
I'm attempting to make a power aura to remind me when Faerie Fire isn't up on the enemy target. So far my issue is that the Enemy Target option doesn't seem to work.

The first image shows the setting i'm using. I'm in combat, the enemy is targeted and have no FF on it.  A icon shows up in the middle of my screen as intended.
https://imgur.com/a/6CI0o8Q

In the 2nd image I use FF on my target and the icon disappears from my screen. It seems like it's working as intended.
https://imgur.com/a/maMRq5o

In the 3rd image I try targeting myself while in combat. The FF icon shows up even though it should only be showing when i'm targeting an enemy. 
https://imgur.com/a/2voUpWe

The same thing happens if I try targeting someone i'm in group with. The Faerie fire icon still shows when in combat.

**Comment by tdymel** [comment]
Fixed, thanks!
Please retest, because I have no vanilla client to test it.

**Comment by Wushengg** [comment]
The command /mpowa no longer works to open the options so I can't test.
